name: MAAT Daily Scrape

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:

jobs:
  scrape:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run MAAT ingestion
        run: |
          python src/ingestion.py

      - name: Commit updated data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add data/

          git commit -m "MAAT automated daily ingestion" || echo "No changes"

          git pull --rebase origin main
          
          git push
